// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © smrti

//@version=5
//initial capital 10000USDT
strategy("1h_bullish_buy_15min_bearish_sell", overlay=true, calc_on_every_tick=true,
 default_qty_type=strategy.percent_of_equity, default_qty_value = 100,
 initial_capital = 10000, currency = currency.USDT, process_orders_on_close=true,
 use_bar_magnifier = true, precision=7)

// timewindow
start = timestamp(2019, 1, 1, 00, 00)            // backtest start  window
end = timestamp(2022, 8, 20, 00, 00)              // backtest end  window
window = time >= start and time <= end

// indicators

ma90 = ta.sma(close, 90)
ma90_1h = request.security(syminfo.tickerid, '60', ma90)
ema50_15 = request.security(syminfo.tickerid, '15', ta.ema(close, 50))
ma90_15 = request.security(syminfo.tickerid, '15', ma90)
vwap = ta.vwap(hlc3, timeframe.change('1D'))

plot(ema50_15, color=color.new(color.red, 20))
plot(ma90_15, color=color.new(color.green, 20))
plot(vwap, color=color.new(color.blue, 20))
plot(ma90_1h, color=color.new(color.yellow, 20))


// conditional indicators
bull_1h = ta.crossover(vwap, ma90_1h)
bear_1h = ta.crossunder(vwap, ma90_1h)
bull_15min = ta.crossover(ema50_15, ma90_15)
bear_15min = ta.crossunder(ema50_15, ma90_15)


// in 1h bull zone
if vwap >= ma90_1h and window
    if bull_15min
        strategy.entry("buy", strategy.long)
    if bear_15min and strategy.position_size > 0
        strategy.close("buy", qty_percent = 100)


// 1h bull
if bull_1h and window
    strategy.entry("buy", strategy.long)

// 1h bear
if bear_1h and strategy.position_size > 0 and window
    strategy.close("buy", qty_percent = 100)

